### ISSUE TITLE
when init

### ISSUE THREAD

**Issue by lybrooks** [railsjack/react-native-mathjax-svg#1]
Unable to resolve module react-native-svg   from the module

**Comment by railsjack** [comment]
I will add it to peerDependencies/dependencies if missing.

**Comment by railsjack** [comment]
OMG, I forgot to add necessary dependencies.
I will add them and make an example using this package.
Thank you for pointing.

**Comment by railsjack** [comment]
I updated the README and example. Please refer to it.
And please pay attention that I added this line.
```
yarn add react-native-mathjax-svg react-native-svg
```
